name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  verbs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: devcontainers/ci@v0.3
        with:
          runCmd: just install-all && just check-all && just test-all
